// İnşaat / mimarlık terimleri — panelde kayan şeritte gösterilir.
// (Kaynak: yaygın Türkçe inşaat terimleri sözlüğü; ihtiyaca göre
// düzenlenebilir/çoğaltılabilir.)
export interface Term {
  term: string;
  def: string;
}

export const CONSTRUCTION_TERMS: Term[] = [
  { term: "Agrega", def: "Betonun içindeki kum, çakıl, kırmataş gibi taneli dolgu malzemeleri." },
  { term: "Aplikasyon", def: "Projedeki yapının araziye ölçülerle işaretlenerek uygulanması." },
  { term: "Rölöve", def: "Mevcut bir yapının ölçülü olarak çizilip belgelenmesi." },
  { term: "Restitüsyon", def: "Yapının özgün (ilk) halinin araştırmayla yeniden çizilmesi." },
  { term: "Restorasyon", def: "Tarihi yapının özgününe uygun onarılıp korunması." },
  { term: "Subasman", def: "Temel üstü ile zemin kat döşemesi arasındaki duvar/kısım." },
  { term: "Hatıl", def: "Duvarları yatayda bağlayan betonarme/ahşap kuşak eleman." },
  { term: "Lento", def: "Kapı ve pencere boşluklarının üzerine oturan taşıyıcı kiriş." },
  { term: "Mahya", def: "Çatının en üst, iki eğik yüzeyin birleştiği tepe çizgisi." },
  { term: "Saçak", def: "Çatının dış duvardan dışarı taşan alt bölümü." },
  { term: "Konsol", def: "Bir ucu ankastre, diğer ucu boşta olan taşıyıcı çıkma eleman." },
  { term: "Döşeme", def: "Katları birbirinden ayıran yatay taşıyıcı plak." },
  { term: "Radye Temel", def: "Yapının tümünü tek bir betonarme plak ile taşıyan temel." },
  { term: "Gabari", def: "İmar planınca izin verilen azami yapı yüksekliği." },
  { term: "Emsal (KAKS)", def: "Kat Alanı Kat Sayısı; toplam inşaat alanının arsaya oranı." },
  { term: "TAKS", def: "Taban Alanı Kat Sayısı; yapının taban alanının arsaya oranı." },
  { term: "Aks", def: "Taşıyıcı elemanların yerini belirleyen referans eksen çizgileri." },
  { term: "Kolon", def: "Düşey yükleri taşıyıp temele aktaran düşey taşıyıcı." },
  { term: "Kiriş", def: "Döşeme yüklerini kolonlara aktaran yatay taşıyıcı." },
  { term: "Perde Duvar", def: "Yatay yükleri karşılayan betonarme taşıyıcı duvar." },
  { term: "Donatı", def: "Betonun çekme dayanımını artıran çelik çubuklar." },
  { term: "Etriye", def: "Boyuna donatıyı saran, kesme kuvvetine çalışan enine donatı." },
  { term: "Grobeton", def: "Temel altına dökülen düşük dozlu tesviye/yalıtım betonu." },
  { term: "Şap", def: "Döşeme üzerine çekilen düzeltme/kaplama altı harç tabakası." },
  { term: "İstinat Duvarı", def: "Zemin kaymasını/toprak itkisini karşılayan dayanma duvarı." },
  { term: "Menfez", def: "Su/geçiş için yol veya dolgu altına yapılan küçük açıklık." },
  { term: "Drenaj", def: "Zemindeki/yapıdaki suyun toplanıp uzaklaştırılması." },
  { term: "İzolasyon", def: "Su, ısı veya sese karşı yalıtım yapılması." },
  { term: "Parapet", def: "Çatı, balkon veya teras kenarındaki koruyucu bordür/duvar." },
  { term: "Denizlik", def: "Pencere altına suyu dışarı atmak için konan eğimli eşik." },
  { term: "Pervaz", def: "Kapı/pencere kenarını çevreleyen bitiş/kaplama profili." },
  { term: "Süpürgelik", def: "Duvar ile döşeme birleşimini kapatan alt bordür." },
  { term: "Asmolen Döşeme", def: "Kirişler arasına dolgu bloklar konularak yapılan döşeme." },
  { term: "Kaset Döşeme", def: "İki yönlü nervürlerle oluşan, kaset görünümlü döşeme." },
  { term: "Fore Kazık", def: "Zeminde açılan deliğe yerinde dökülen betonarme kazık." },
  { term: "Zemin Etüdü", def: "Zeminin taşıma gücü ve özelliklerinin araştırılması." },
  { term: "Vaziyet Planı", def: "Yapının arsa üzerindeki konumunu gösteren plan." },
  { term: "İfraz", def: "Bir parselin birden fazla parsele bölünmesi." },
  { term: "Tevhit", def: "Birden fazla parselin birleştirilerek tek parsel yapılması." },
  { term: "DOP", def: "Düzenleme Ortaklık Payı; kamu alanları için terk edilen pay." },
  { term: "Çekme Mesafesi", def: "Yapının komşu sınır/yoldan bırakması gereken uzaklık." },
  { term: "Kot", def: "Bir noktanın referans düzleme göre yükseklik değeri." },
  { term: "Ruhsat", def: "Yapının imara uygun inşasına verilen resmi izin." },
  { term: "İskan", def: "Tamamlanan yapının kullanımına verilen izin (yapı kullanma izni)." },
  { term: "Müellif", def: "Projeyi hazırlayan ve imzalayan yetkili mimar/mühendis." },
  { term: "Harç (İnşaat)", def: "Çimento/kireç, kum ve su karışımı bağlayıcı malzeme." },
  { term: "Sıva", def: "Duvar yüzeyini düzeltip koruyan harç kaplaması." },
  { term: "Kalıp", def: "Betonun dökülüp şekil aldığı geçici form." },
  { term: "İskele", def: "Yüksekte çalışma için kurulan geçici platform sistemi." },
  { term: "Nervür", def: "Döşeme altındaki ince, sık kirişçikler." },
  { term: "Mesnet", def: "Taşıyıcı elemanın yükünü aktardığı destek noktası." },
  { term: "Brüt Alan", def: "Duvarlar dahil, dış ölçülerden hesaplanan toplam alan." },
  { term: "Net Alan", def: "Kullanılabilir, duvarlar hariç iç alan." },
  { term: "Palplanş", def: "Kazıyı tutmak için zemine çakılan iç içe geçen çelik levhalar." },
  { term: "Grobeton", def: "Zemin ile temel arasında tesviye amaçlı zayıf beton." },
  { term: "Rögar", def: "Altyapı hatlarına erişim/temizlik için yapılan bakım bacası." },
  { term: "Mütemmim Cüz", def: "Ana yapıya bağlı, ayrılması mümkün olmayan tamamlayıcı bölüm." },
  { term: "Kat İrtifakı", def: "Henüz tamamlanmamış yapıda bağımsız bölüm üzerindeki hak." },
  { term: "Kat Mülkiyeti", def: "Tamamlanmış yapıda bağımsız bölüm üzerindeki tam mülkiyet." },
  { term: "Vekaletname", def: "Bir işin başkası adına yürütülmesi için verilen yetki belgesi." },
];
